version: '2'

services:
  jackett:
    image: lsioarmhf/jackett
    container_name: jackett_container_compose
    restart: always
    ports:
      - '9117:9117'
    volumes:
      - "./config:/config"
      - "/torrents:/downloads"
    env_file: 
      - ./common.env
    network_mode: "host"
